### ISSUE TITLE
    TerminalParameterId 需要补充

### ISSUE THREAD

**Issue by Super-Jun-Jie** [zhoyq/spring-boot-starter-jt808#11]
TerminalParameterId 需要补充
/**
     * 服务器 TCP 端口
     */
    ServerTCPPort(new byte[]{0x00, 0x00, 0x00, 0x18}),
    /**
     * 服务器 UDP 端口
     */
    ServerUDPPort(new byte[]{0x00, 0x00, 0x00, 0x19}),

1078协议上的  0075  0076 0077 需要进一步解析 我还没有做

**Comment by zhoyq-work** [comment]
完成 1078 和 苏标之后 这部分有问题的地方会完善的，目前还处于开发阶段
